### ISSUE TITLE
Program Description not properly processed

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#98]
The `info` arrgument returned to the callback [here](https://github.com/DVBProject/DVB-I-Reference-Client/blob/4786fd1016cbe99511c43578b1acafc881ab76b6/frontend/android/js/program.js#L155)
````
  this.channel.getProgramInfo(this.programId, function (info) {
    var i;
    if (info) {
      console.log(typeof info);
````
is just an untyped object declared as `var program={};` in  [channel-common.js:42](https://github.com/DVBProject/DVB-I-Reference-Client/blob/4786fd1016cbe99511c43578b1acafc881ab76b6/frontend/channel-common.js#L42)

As such, the subsequent processing of this object fails with two traceback messages...
````
program.js:139 Uncaught TypeError: episodes[i].getTitle is not a function
    at Function.<anonymous> (program.js:139:23)
    at Object.success (channel-common.js:259:18)
    at c (jquery-3.4.1.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2:28487)
    at l (jquery-3.4.1.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.min.js:2:81117)
````
and 
````
program.js:187 Uncaught TypeError: info.getLongDescription is not a function
    at Function.<anonymous> (program.js:187:27)
    at Object.success (channel-common.js:276:20)
    at c (jquery-3.4.1.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2:28487)
    at l (jquery-3.4.1.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.min.js:2:81117)
````

The object should have either been [constructed as](https://github.com/DVBProject/DVB-I-Reference-Client/blob/4786fd1016cbe99511c43578b1acafc881ab76b6/frontend/android/js/program.js#L1), or cast to, a Program object for these methods to be available..

**Comment by paulhiggs** [comment]
PR #99 is merged to resolve this.
